name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk
          pip install buildozer cython
      - name: Force Patch Buildozer to use build-tools 34
        run: |
          # 找到 buildozer 的安卓脚本，强制把 37.0.0 替换为 34.0.0
          FILE=$(python -c "import buildozer.targets.android; print(buildozer.targets.android.__file__)")
          echo "Patching file: $FILE"
          sudo sed -i "s/'build-tools;37.0.0'/'build-tools;34.0.0'/g" $FILE
          sudo sed -i "s/\"build-tools;37.0.0\"/\"build-tools;34.0.0\"/g" $FILE
          grep "build-tools" $FILE
      - name: Build APK
        run: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: susi-apk
          path: bin/*.apk
